name: Deploy documentation

on:
  schedule:
    - cron: "* 0 * * *"
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Load cached node modules
        id: cached-npm-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'

      - name: Generate static build
        run: npm run build

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
          token: ${{ secrets.PAT }}
          clean: true
